version: "3.9"

services:

  web:
    build: .
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
      - ./public/static:/app/public/static
    ports:
      - "8089:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=Floor_Bot.settings
    depends_on:
      - redis
    restart: always
    networks:
      - floor_network

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - floor_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5

  celery:
    build: .
    command: celery -A Floor_Bot worker -l info
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - .env
    depends_on:
      - redis
      - web
    restart: always
    networks:
      - floor_network

networks:
  floor_network:
    driver: bridge