# Generated by Django 6.0 on 2026-02-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_customuser_address_line_i_customuser_address_line_ii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='delivery_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
