# Generated by Django 6.0 on 2026-01-08 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(unique=True)),
                ('image', models.ImageField(upload_to='categoris')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='products')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=250)),
                ('brand_manufacturer', models.CharField(max_length=250)),
                ('item_description', models.CharField(blank=True, max_length=250, null=True)),
                ('primary_image', models.ImageField(upload_to='products')),
                ('regular_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product_id', models.CharField(max_length=250, unique=True)),
                ('pack_coverage', models.CharField(max_length=250)),
                ('length', models.CharField(max_length=250)),
                ('width', models.CharField(max_length=250)),
                ('thickness', models.CharField(max_length=250)),
                ('weight', models.CharField(max_length=250)),
                ('installation_method', models.CharField(max_length=250)),
                ('coverage_per_pack', models.CharField(max_length=250)),
                ('pile_height', models.CharField(max_length=250)),
                ('materials', models.TextField(blank=True)),
                ('format', models.CharField(max_length=250)),
                ('is_underlay_required', models.BooleanField(default=False)),
                ('available_colors', models.TextField(blank=True)),
                ('pattern_type', models.CharField(max_length=250)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('total_salses', models.IntegerField(default=0)),
                ('images', models.ManyToManyField(blank=True, related_name='images', to='dashboard.images')),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.category')),
                ('sub_category', models.ManyToManyField(blank=True, to='dashboard.subcategory')),
            ],
        ),
    ]
