# Generated by Django 6.0 on 2026-01-12 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_product_created_at_alter_product_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('ship_method', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(default='', max_length=250)),
                ('carrier', models.CharField(blank=True, max_length=250, null=True)),
                ('tracking_no', models.CharField(blank=True, null=True, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_shiped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_or_region', models.CharField(blank=True, max_length=250, null=True)),
                ('address_line_i', models.CharField(blank=True, max_length=250, null=True)),
                ('address_line_ii', models.CharField(blank=True, max_length=250, null=True)),
                ('suburb', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
