# Generated by Django 6.0 on 2026-01-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_ordertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='tax_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
