# Generated by Django 6.0 on 2026-01-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_ordertable_delivery_fee_ordertable_tax_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], default='placed', max_length=250),
        ),
    ]
