# Generated by Django 6.0 on 2026-01-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_ordertable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='custormer_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='is_feedbacked',
            field=models.BooleanField(default=False),
        ),
    ]
