# Generated by Django 6.0 on 2026-01-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_ordertable_custormer_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='placed', max_length=250),
        ),
    ]
