# Generated by Django 6.0 on 2026-01-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_ordertable_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertable',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='is_calculate',
            field=models.BooleanField(default=False),
        ),
    ]
