# Generated by Django 6.0 on 2026-01-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_ordertable_options_product_is_calculate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='paid_ammount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
