# Generated by Django 6.0 on 2026-01-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_ordertable_paid_ammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='delivary_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
