# Generated by Django 6.0 on 2026-01-31 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_ordertable_delivary_fee_product_tax_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='delivary_fee',
        ),
    ]
