# Generated by Django 6.0 on 2026-02-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_product_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.TextField(default='30-day return policy. Items must be in original condition with packaging. Return shipping costs may apply.'),
        ),
    ]
