# Generated by Django 6.0 on 2026-02-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_product_return_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
