# Generated by Django 6.0 on 2026-02-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_ordertable_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
