# Generated by Django 6.0 on 2026-04-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_product_tags_alter_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='products',
            field=models.ManyToManyField(related_name='product_lists', to='dashboard.product'),
        ),
    ]
