# Generated by Django 6.0 on 2026-04-13 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_ordertable_product_remove_ordertable_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordertable',
            name='products',
            field=models.ManyToManyField(related_name='product_lists', to='dashboard.product'),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='quantity',
            field=models.IntegerField(default=77),
            preserve_default=False,
        ),
    ]
