# Generated by Django 6.0 on 2026-04-13 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_ordertable_product_ordertable_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_lists', to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
