# Generated by Django 6.0 on 2026-04-13 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_ordertable_product_alter_ordertable_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='products',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='quantity',
        ),
    ]
